In [2]:
import numpy as np

1. Create a null vector of size 10 but the fifth value which is 1

In [6]:
print((np.arange(10) == 4) * 1)

[0 0 0 0 1 0 0 0 0 0]


2. Create a vector with values ranging from 10 to 49.

In [11]:
Vector = np.arange(10,50)
print(Vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


3. Create a 3x3 matrix with values ranging from 0 to 8

In [13]:
vector = np.arange(9).reshape(3,3)
print(vector)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [24]:
vector = [1,2,0,0,4,0]
print(np.nonzero(vector))

(array([0, 1, 4], dtype=int64),)


5. Create a 10x10 array with random values and find the minimum and maximum values.

In [42]:
array = np.random.randint(low = 10, high = 500, size = (10,10))

print("\nMax value from array is {}".format(np.max(array)))
print("\nMin value from array is {}".format(np.min(array)))

[[280 481 144  56 225 140  94 470 430 426]
 [ 17 189 185 366 172  41 246 168  33 368]
 [411 131 377 281 277 233  29 239 388 288]
 [ 21 357 467 412 227  19 263 489 359 204]
 [ 74  84  40 451 245 163 150 367  12 351]
 [354  99 142  58 302 279 496 351 358  30]
 [369 468 309 362 105 434 341  60 124 140]
 [122 330 484 174 410 141 320 171 450 465]
 [400 409  16  20 459 173  95  35 247 333]
 [490 415 159 263 419 295 127 387 312 399]]

Max value from array is 496

Min value from array is 12


6. Create a random vector of size 30 and find the mean value.

In [58]:
np.random.seed(0)
array = np.random.randint(low = 10, high = 500, size = (30))

print("Mean of array is {}".format(np.mean(array)))

Mean of array is 213.76666666666668
